name: "Linting"

on:
  push:
    paths:
      - './**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - './**'

jobs:
  # Non-blocking job that checks .md file locations and also lints them
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: "Validate markdown file locations"
        continue-on-error: true
        run: "scripts/check-markdown-files.sh" 
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9
        continue-on-error: true
        with:
          command: config
          globs: |
            ./custom.markdownlint.jsonc
            **/*.md

  
